remote_theme: andrewbanchich/forty-jekyll-theme
title: Steven T. Barnhart
email: barnhart.steve@gmail.com
linkedin_url: https://www.linkedin.com/in/stevenbarnhart
mastodon: @Steve@runfastr.com
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2
include: [ "/.well-known" ]
